import Head from 'next/head';
import Navbar from '../components/navs/Navbar';
import Hero from '../components/Hero';
import Whatlof from '../components/whatlof';
import Lofplatform from '../components/Lofplatform';
import Footer from '../components/navs/Footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
<Hero/>
<Whatlof/>
<Lofplatform/>
     <Footer/>
    </>
  )
}
